//############### JDBC ############

###default
POST http://localhost:8080/jdbc

###fetch-size = 100
POST http://localhost:8080/jdbc/fetch-size


//############### JDBC TEMPLATE ############

###fetch-size = 100
POST http://localhost:8080/jdbc/template/pr?prReadOnly=false&prAutoCommit=true

###fetch-size = 100, read only on, auto commit off
POST http://localhost:8080/jdbc/template/pr?prReadOnly=true&prAutoCommit=false

###fetch-size = 100, read only on, auto commit on
POST http://localhost:8080/jdbc/template/pr?prReadOnly=true&prAutoCommit=true

###fetch-size = 100, read only off, auto commit on
POST http://localhost:8080/jdbc/template/pr?prReadOnly=false&prAutoCommit=true


//############### JDBC TEMPLATE TRANSACTIONAL ############

###fetch-size = 100
POST http://localhost:8080/jdbc/template-transactional/pr?prReadOnly=false&prAutoCommit=true

###fetch-size = 100, read only on, auto commit off
POST http://localhost:8080/jdbc/template-transactional/pr?prReadOnly=true&prAutoCommit=false

###fetch-size = 100, read only on, auto commit on
POST http://localhost:8080/jdbc/template-transactional/pr?prReadOnly=true&prAutoCommit=true

###fetch-size = 100, read only off, auto commit on
POST http://localhost:8080/jdbc/template-transactional/pr?prReadOnly=false&prAutoCommit=true


//############### JPA STREAM ############

###fetch-size = 100
POST http://localhost:8080/jpa/fetch-size

###fetch-size = 100, read only on, cacheable off
POST http://localhost:8080/jpa/read-only-fetch-size

###fetch-size = 100, read only on, cacheable on
POST http://localhost:8080/jpa/read-only-and-cache-fetch-size

###fetch-size = 100, read only off, cacheable on
POST http://localhost:8080/jpa/cache-fetch-size


//############### JPA STREAM DETACH ############

###fetch-size = 100
POST http://localhost:8080/jpa/detach/fetch-size

###fetch-size = 100, read only on, cacheable off
POST http://localhost:8080/jpa/detach/read-only-fetch-size

###fetch-size = 100, read only on, cacheable on
POST http://localhost:8080/jpa/detach/read-only-and-cache-fetch-size

###fetch-size = 100, read only off, cacheable on
POST http://localhost:8080/jpa/detach/cache-fetch-size

//############### HIBERNATE SCROLLABLERESULTS ############

###fetch-size = 100
POST http://localhost:8080/scrollable

